server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
  tomcat:
    max-http-form-post-size: 10485760
spring:
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      data-locations: classpath:db/data.sql
      mode: always
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    generate-ddl: true
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

screenshot:
  path: C:\Users\HoHyeon Kim\IdeaProjects\spring-gdic\screenshot
application:
  url: http://localhost:8080
